var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
var car1 = 'Honda';
console.log("Is car1 == 'Honda'? I predict True.");
console.log(car1 == 'Honda');
var bike = 'ybr g';
console.log("Is bike == 'ybr g'? I predict True.");
console.log(bike == 'ybr g');
var watch = 'apple watch';
console.log("Is watch == 'apple watch'? I predict True.");
console.log(watch == 'apple watch');
var phone = 'Iphone 15 pro max';
console.log("Is phone = 'Iphone 15 pro max'? I predict True.");
console.log(phone == 'Iphone 15 pro max');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car1 != 'Honda'? I predict False.");
console.log(car1 != 'Honda');
console.log("Is bike != 'ybr g'? I predict False.");
console.log(bike != 'ybr g');
console.log("Is watch != 'apple watch'? I predict False.");
console.log(watch != 'apple watch');
console.log("Is phone != 'Iphone 15 pro max'? I predict False.");
console.log(phone != 'Iphone 15 pro max');
